"""Add abbreviation field to institution history

Revision ID: 64e2537f10a4
Revises: 
Create Date: 2025-12-04 17:33:49.655752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e2537f10a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions_historique', sa.Column('Institution_abbreviation_historique', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_examen',
    sa.Column('SessionExamen_id', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('SessionExamen_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('SessionExamen_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('SessionExamen_id', name='sessions_examen_pkey'),
    sa.UniqueConstraint('SessionExamen_code', name='sessions_examen_SessionExamen_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('SessionExamen_label', name='sessions_examen_SessionExamen_label_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('cycles',
    sa.Column('Cycle_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Cycle_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('Cycle_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Cycle_id', name='cycles_pkey'),
    sa.UniqueConstraint('Cycle_code', name='cycles_Cycle_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('Cycle_label', name='cycles_Cycle_label_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('types_formation',
    sa.Column('TypeFormation_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('TypeFormation_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('TypeFormation_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('TypeFormation_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('TypeFormation_id', name='types_formation_pkey'),
    sa.UniqueConstraint('TypeFormation_code', name='types_formation_TypeFormation_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('TypeFormation_label', name='types_formation_TypeFormation_label_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('institutions',
    sa.Column('Institution_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Institution_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('Institution_nom', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Institution_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Institution_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Institution_abbreviation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Institution_logo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Institution_id', name='institutions_pkey'),
    sa.UniqueConstraint('Institution_code', name='uq_institution_code', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('institutions_historique',
    sa.Column('Institution_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('Institution_nom_historique', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Institution_code_historique', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Institution_description_historique', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('institutions_historique_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Institution_id_fk'], ['institutions.Institution_id'], name=op.f('institutions_historique_Institution_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Institution_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('institutions_historique_pkey'))
    )
    op.create_table('composantes',
    sa.Column('Composante_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('Composante_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Composante_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Composante_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Composante_abbreviation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Composante_logo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Institution_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Institution_id_fk'], ['institutions.Institution_id'], name='composantes_Institution_id_fk_fkey'),
    sa.PrimaryKeyConstraint('Composante_id', name='composantes_pkey'),
    sa.UniqueConstraint('Composante_code', name='uq_composante_code', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('cycles_historique',
    sa.Column('Cycle_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('Cycle_label_historique', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('cycles_historique_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Cycle_id_fk'], ['cycles.Cycle_id'], name=op.f('cycles_historique_Cycle_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Cycle_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('cycles_historique_pkey'))
    )
    op.create_table('notes',
    sa.Column('Note_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Etudiant_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('EC_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('SessionExamen_id_fk', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('Note_valeur', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('notes_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['EC_id_fk'], ['elements_constitutifs.EC_id'], name=op.f('notes_EC_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Etudiant_id_fk'], ['etudiants.Etudiant_id'], name=op.f('notes_Etudiant_id_fk_fkey')),
    sa.ForeignKeyConstraint(['SessionExamen_id_fk'], ['sessions_examen.SessionExamen_id'], name=op.f('notes_SessionExamen_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Note_id', name=op.f('notes_pkey')),
    sa.UniqueConstraint('Etudiant_id_fk', 'EC_id_fk', 'AnneeUniversitaire_id_fk', 'SessionExamen_id_fk', name=op.f('uq_etudiant_ec_annee_session'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('jurys',
    sa.Column('Jury_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Enseignant_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Semestre_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('Jury_date_nomination', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('jurys_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Enseignant_id_fk'], ['enseignants.Enseignant_id'], name=op.f('jurys_Enseignant_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Semestre_id_fk'], ['semestres.Semestre_id'], name=op.f('jurys_Semestre_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Jury_id', name=op.f('jurys_pkey')),
    sa.UniqueConstraint('Semestre_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('uq_jury_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('unites_enseignement',
    sa.Column('UE_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('UE_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('UE_intitule', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('UE_credit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Semestre_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Parcours_id_fk', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name='unites_enseignement_AnneeUniversitaire_id_fk_fkey'),
    sa.ForeignKeyConstraint(['Parcours_id_fk'], ['parcours.Parcours_id'], name='unites_enseignement_Parcours_id_fk_fkey'),
    sa.ForeignKeyConstraint(['Semestre_id_fk'], ['semestres.Semestre_id'], name='unites_enseignement_Semestre_id_fk_fkey'),
    sa.PrimaryKeyConstraint('UE_id', name='unites_enseignement_pkey'),
    sa.UniqueConstraint('UE_code', 'Parcours_id_fk', 'AnneeUniversitaire_id_fk', name='uq_ue_code_parcours_annee', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('parcours_niveaux',
    sa.Column('ParcoursNiveau_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Parcours_id_fk', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('Niveau_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('ParcoursNiveau_ordre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('parcours_niveaux_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Niveau_id_fk'], ['niveaux.Niveau_id'], name=op.f('parcours_niveaux_Niveau_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Parcours_id_fk'], ['parcours.Parcours_id'], name=op.f('parcours_niveaux_Parcours_id_fk_fkey')),
    sa.PrimaryKeyConstraint('ParcoursNiveau_id', name=op.f('parcours_niveaux_pkey')),
    sa.UniqueConstraint('Parcours_id_fk', 'Niveau_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('uq_parcours_niveau_annee'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('enseignants',
    sa.Column('Enseignant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Enseignant_matricule', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Enseignant_nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Enseignant_prenoms', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('Enseignant_sexe', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Enseignant_date_naissance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Enseignant_grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Enseignant_statut', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Composante_id_affectation_fk', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('Enseignant_cin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Enseignant_cin_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Enseignant_cin_lieu', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Enseignant_telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Enseignant_mail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Enseignant_rib', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Enseignant_photo_profil_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Enseignant_scan_cin_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint('"Enseignant_statut"::text = ANY (ARRAY[\'PERM\'::character varying, \'VAC\'::character varying]::text[])', name='check_statut_enseignant'),
    sa.ForeignKeyConstraint(['Composante_id_affectation_fk'], ['composantes.Composante_id'], name='enseignants_Composante_id_affectation_fk_fkey'),
    sa.PrimaryKeyConstraint('Enseignant_id', name='enseignants_pkey'),
    sa.UniqueConstraint('Enseignant_cin', name='uq_enseignant_cin', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('Enseignant_matricule', name='enseignants_Enseignant_matricule_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('resultats_semestre',
    sa.Column('ResultatSemestre_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Etudiant_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Semestre_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('SessionExamen_id_fk', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('ResultatSemestre_statut_validation', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('ResultatSemestre_credits_acquis', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('ResultatSemestre_moyenne_obtenue', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.CheckConstraint('"ResultatSemestre_statut_validation"::text = ANY (ARRAY[\'V\'::character varying, \'NV\'::character varying, \'AJ\'::character varying]::text[])', name=op.f('check_statut_validation')),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('resultats_semestre_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Etudiant_id_fk'], ['etudiants.Etudiant_id'], name=op.f('resultats_semestre_Etudiant_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Semestre_id_fk'], ['semestres.Semestre_id'], name=op.f('resultats_semestre_Semestre_id_fk_fkey')),
    sa.ForeignKeyConstraint(['SessionExamen_id_fk'], ['sessions_examen.SessionExamen_id'], name=op.f('resultats_semestre_SessionExamen_id_fk_fkey')),
    sa.PrimaryKeyConstraint('ResultatSemestre_id', name=op.f('resultats_semestre_pkey')),
    sa.UniqueConstraint('Etudiant_id_fk', 'Semestre_id_fk', 'AnneeUniversitaire_id_fk', 'SessionExamen_id_fk', name=op.f('uq_resultat_semestre_session'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('types_enseignement',
    sa.Column('TypeEnseignement_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('TypeEnseignement_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('TypeEnseignement_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('TypeEnseignement_id', name='types_enseignement_pkey'),
    sa.UniqueConstraint('TypeEnseignement_code', name='types_enseignement_TypeEnseignement_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('TypeEnseignement_label', name='types_enseignement_TypeEnseignement_label_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('resultats_ue',
    sa.Column('ResultatUE_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Etudiant_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('UE_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('SessionExamen_id_fk', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('ResultatUE_moyenne', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('ResultatUE_is_acquise', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ResultatUE_credit_obtenu', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('resultats_ue_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Etudiant_id_fk'], ['etudiants.Etudiant_id'], name=op.f('resultats_ue_Etudiant_id_fk_fkey')),
    sa.ForeignKeyConstraint(['SessionExamen_id_fk'], ['sessions_examen.SessionExamen_id'], name=op.f('resultats_ue_SessionExamen_id_fk_fkey')),
    sa.ForeignKeyConstraint(['UE_id_fk'], ['unites_enseignement.UE_id'], name=op.f('resultats_ue_UE_id_fk_fkey')),
    sa.PrimaryKeyConstraint('ResultatUE_id', name=op.f('resultats_ue_pkey')),
    sa.UniqueConstraint('Etudiant_id_fk', 'UE_id_fk', 'AnneeUniversitaire_id_fk', 'SessionExamen_id_fk', name=op.f('uq_resultat_ue_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('etudiants',
    sa.Column('Etudiant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Etudiant_numero_inscription', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Etudiant_nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Etudiant_prenoms', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('Etudiant_sexe', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Etudiant_naissance_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Etudiant_naissance_lieu', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Etudiant_nationalite', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Etudiant_bacc_annee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Etudiant_bacc_serie', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Etudiant_bacc_numero', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('Etudiant_bacc_centre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Etudiant_bacc_mention', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Etudiant_adresse', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Etudiant_telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Etudiant_mail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Etudiant_cin', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('Etudiant_cin_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Etudiant_cin_lieu', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Etudiant_photo_profil_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Etudiant_scan_cin_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Etudiant_scan_releves_notes_bacc_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Etudiant_id', name='etudiants_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('parcours_historique',
    sa.Column('Parcours_id_fk', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('Parcours_label_historique', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Parcours_code_historique', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('parcours_historique_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Parcours_id_fk'], ['parcours.Parcours_id'], name=op.f('parcours_historique_Parcours_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Parcours_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('parcours_historique_pkey'))
    )
    op.create_table('inscriptions',
    sa.Column('Inscription_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Etudiant_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('Parcours_id_fk', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('Semestre_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ModeInscription_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('Inscription_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('Inscription_credit_acquis_semestre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Inscription_is_semestre_valide', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('inscriptions_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Etudiant_id_fk'], ['etudiants.Etudiant_id'], name=op.f('inscriptions_Etudiant_id_fk_fkey')),
    sa.ForeignKeyConstraint(['ModeInscription_id_fk'], ['modes_inscription.ModeInscription_id'], name=op.f('inscriptions_ModeInscription_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Parcours_id_fk'], ['parcours.Parcours_id'], name=op.f('inscriptions_Parcours_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Semestre_id_fk'], ['semestres.Semestre_id'], name=op.f('inscriptions_Semestre_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Inscription_id', name=op.f('inscriptions_pkey')),
    sa.UniqueConstraint('Etudiant_id_fk', 'AnneeUniversitaire_id_fk', 'Parcours_id_fk', 'Semestre_id_fk', name=op.f('uq_etudiant_annee_parcours_semestre'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('parcours',
    sa.Column('Parcours_id', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('Parcours_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Parcours_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Parcours_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Parcours_abbreviation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Parcours_logo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Parcours_date_creation', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Parcours_date_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Mention_id_fk', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('Parcours_type_formation_defaut_id_fk', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Mention_id_fk'], ['mentions.Mention_id'], name='parcours_Mention_id_fk_fkey'),
    sa.ForeignKeyConstraint(['Parcours_type_formation_defaut_id_fk'], ['types_formation.TypeFormation_id'], name='parcours_Parcours_type_formation_defaut_id_fk_fkey'),
    sa.PrimaryKeyConstraint('Parcours_id', name='parcours_pkey'),
    sa.UniqueConstraint('Parcours_code', 'Mention_id_fk', name='unique_parcours_code_mention', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('niveaux',
    sa.Column('Niveau_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Niveau_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('Niveau_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Cycle_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Cycle_id_fk'], ['cycles.Cycle_id'], name='niveaux_Cycle_id_fk_fkey'),
    sa.PrimaryKeyConstraint('Niveau_id', name='niveaux_pkey'),
    sa.UniqueConstraint('Niveau_code', name='niveaux_Niveau_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('affectations_ec',
    sa.Column('AffectationEC_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Enseignant_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('EC_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('TypeEnseignement_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('AffectationEC_volume_heure_effectif', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('affectations_ec_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['EC_id_fk'], ['elements_constitutifs.EC_id'], name=op.f('affectations_ec_EC_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Enseignant_id_fk'], ['enseignants.Enseignant_id'], name=op.f('affectations_ec_Enseignant_id_fk_fkey')),
    sa.ForeignKeyConstraint(['TypeEnseignement_id_fk'], ['types_enseignement.TypeEnseignement_id'], name=op.f('affectations_ec_TypeEnseignement_id_fk_fkey')),
    sa.PrimaryKeyConstraint('AffectationEC_id', name=op.f('affectations_ec_pkey')),
    sa.UniqueConstraint('EC_id_fk', 'TypeEnseignement_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('uq_affectation_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('niveaux_historique',
    sa.Column('Niveau_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('Niveau_label_historique', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('niveaux_historique_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Niveau_id_fk'], ['niveaux.Niveau_id'], name=op.f('niveaux_historique_Niveau_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Niveau_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('niveaux_historique_pkey'))
    )
    op.create_table('semestres',
    sa.Column('Semestre_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Semestre_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('Semestre_numero', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('Niveau_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Niveau_id_fk'], ['niveaux.Niveau_id'], name='semestres_Niveau_id_fk_fkey'),
    sa.PrimaryKeyConstraint('Semestre_id', name='semestres_pkey'),
    sa.UniqueConstraint('Niveau_id_fk', 'Semestre_numero', name='uq_niveau_numero_semestre', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('Semestre_code', name='semestres_Semestre_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('domaines',
    sa.Column('Domaine_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Domaine_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Domaine_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Domaine_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Domaine_id', name='domaines_pkey'),
    sa.UniqueConstraint('Domaine_code', name='domaines_Domaine_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('mentions_historique',
    sa.Column('Mention_id_fk', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('Mention_label_historique', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Mention_code_historique', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('mentions_historique_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Mention_id_fk'], ['mentions.Mention_id'], name=op.f('mentions_historique_Mention_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Mention_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('mentions_historique_pkey'))
    )
    op.create_table('annees_universitaires',
    sa.Column('AnneeUniversitaire_id', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_annee', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('AnneeUniversitaire_ordre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('AnneeUniversitaire_id', name='annees_universitaires_pkey'),
    sa.UniqueConstraint('AnneeUniversitaire_annee', name='annees_universitaires_AnneeUniversitaire_annee_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('AnneeUniversitaire_ordre', name='uq_annee_ordre_unique', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('volume_horaire_ec',
    sa.Column('VolumeHoraireEC_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('EC_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('TypeEnseignement_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('VolumeHoraireEC_volume_heure', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('volume_horaire_ec_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['EC_id_fk'], ['elements_constitutifs.EC_id'], name=op.f('volume_horaire_ec_EC_id_fk_fkey')),
    sa.ForeignKeyConstraint(['TypeEnseignement_id_fk'], ['types_enseignement.TypeEnseignement_id'], name=op.f('volume_horaire_ec_TypeEnseignement_id_fk_fkey')),
    sa.PrimaryKeyConstraint('VolumeHoraireEC_id', name=op.f('volume_horaire_ec_pkey')),
    sa.UniqueConstraint('EC_id_fk', 'TypeEnseignement_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('uq_ec_vh_type_annee'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('mentions',
    sa.Column('Mention_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('Mention_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('Mention_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Mention_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Mention_abbreviation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Mention_logo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Composante_id_fk', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('Domaine_id_fk', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Composante_id_fk'], ['composantes.Composante_id'], name='mentions_Composante_id_fk_fkey'),
    sa.ForeignKeyConstraint(['Domaine_id_fk'], ['domaines.Domaine_id'], name='mentions_Domaine_id_fk_fkey'),
    sa.PrimaryKeyConstraint('Mention_id', name='mentions_pkey'),
    sa.UniqueConstraint('Mention_code', 'Composante_id_fk', name='unique_mention_code_composante', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('suivi_credits_cycles',
    sa.Column('SuiviCreditCycle_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Etudiant_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Cycle_id_fk', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('SuiviCreditCycle_credit_total_acquis', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SuiviCreditCycle_is_cycle_valide', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Cycle_id_fk'], ['cycles.Cycle_id'], name=op.f('suivi_credits_cycles_Cycle_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Etudiant_id_fk'], ['etudiants.Etudiant_id'], name=op.f('suivi_credits_cycles_Etudiant_id_fk_fkey')),
    sa.PrimaryKeyConstraint('SuiviCreditCycle_id', name=op.f('suivi_credits_cycles_pkey')),
    sa.UniqueConstraint('Etudiant_id_fk', 'Cycle_id_fk', name=op.f('uq_etudiant_cycle_credit'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('modes_inscription',
    sa.Column('ModeInscription_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ModeInscription_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ModeInscription_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ModeInscription_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ModeInscription_id', name=op.f('modes_inscription_pkey')),
    sa.UniqueConstraint('ModeInscription_code', name=op.f('modes_inscription_ModeInscription_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('ModeInscription_label', name=op.f('modes_inscription_ModeInscription_label_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('composantes_historique',
    sa.Column('Composante_id_fk', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('AnneeUniversitaire_id_fk', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('Composante_label_historique', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Composante_code_historique', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AnneeUniversitaire_id_fk'], ['annees_universitaires.AnneeUniversitaire_id'], name=op.f('composantes_historique_AnneeUniversitaire_id_fk_fkey')),
    sa.ForeignKeyConstraint(['Composante_id_fk'], ['composantes.Composante_id'], name=op.f('composantes_historique_Composante_id_fk_fkey')),
    sa.PrimaryKeyConstraint('Composante_id_fk', 'AnneeUniversitaire_id_fk', name=op.f('composantes_historique_pkey'))
    )
    op.create_table('elements_constitutifs',
    sa.Column('EC_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('EC_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('EC_intitule', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('EC_coefficient', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('UE_id_fk', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['UE_id_fk'], ['unites_enseignement.UE_id'], name=op.f('elements_constitutifs_UE_id_fk_fkey')),
    sa.PrimaryKeyConstraint('EC_id', name=op.f('elements_constitutifs_pkey')),
    sa.UniqueConstraint('EC_code', 'UE_id_fk', name=op.f('uq_ec_code_ue'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
