"""Update DossierInscription ID type and add Mention relationship

Revision ID: a4aae72abf37
Revises: 
Create Date: 2025-12-15 17:51:37.702087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4aae72abf37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. MODIFICATION DE LA TAILLE DE L'ID (Clé Primaire)
    # L'ID doit être assez grand pour Etudiant_id + "_" + Mention_code (ex: 120 caractères)
    op.alter_column(
        'dossiers_inscription', 
        'DossierInscription_id',
        # Remplacez '50' par la taille actuelle de votre colonne si elle est différente
        existing_type=sa.String(50), 
        type_=sa.String(120),  # Nouvelle taille (suffisante pour la concaténation)
        existing_nullable=False, # Conserver la non-nullité (c'est une PK)
        is_nullable=False,
        schema=None
    )
    
    # 2. AJOUT/RECRÉATION DE LA CONTRAINTE D'UNICITÉ LOGIQUE
    # Pour s'assurer qu'un étudiant n'a qu'un dossier par mention.
    # Si cette contrainte existait déjà et que seul le nom change, il faudrait d'abord op.drop_constraint.
    # Ici, nous assumons qu'Alembic l'ajoute ou la corrige :
    
    # 3. (OPTIONNEL) Si vous aviez omis une clé étrangère auparavant, Alembic l'ajouterait ici:
    # op.create_foreign_key(
    #     'fk_dossiers_inscription_mention', 
    #     'dossiers_inscription', 
    #     'mentions', 
    #     ['Mention_id_fk'], 
    #     ['Mention_id']
    # )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Annulation de la contrainte d'unicité
    op.drop_constraint('uq_etudiant_mention_dossier', 'dossiers_inscription', type_='unique')
    
    # Rétablissement de la taille de l'ID à l'original (ATTENTION À LA PERTE DE DONNÉES!)
    # Si la base de données contient des IDs longs (générés par le nouveau format), 
    # cette opération ÉCHOUERA ou TRONQUERA les données.
    op.alter_column(
        'dossiers_inscription', 
        'DossierInscription_id',
        existing_type=sa.String(120),
        type_=sa.String(50), # Rétablir la taille initiale
        existing_nullable=False,
        is_nullable=False,
        schema=None
    )
    
    # ### end Alembic commands ###
