"""Add description and abbreviation to ParcoursHistorique

Revision ID: c65f8e33556b
Revises: 26988f595f7d
Create Date: 2025-12-05 18:20:38.682611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65f8e33556b'
down_revision: Union[str, Sequence[str], None] = '26988f595f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🆕 Ajout de la colonne pour l'abréviation
    op.add_column('parcours_historique', sa.Column('Parcours_abbreviation_historique', sa.String(length=20), nullable=True))
    
    # 🆕 Ajout de la colonne pour la description
    op.add_column('parcours_historique', sa.Column('Parcours_description_historique', sa.Text(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🗑️ Suppression de la colonne pour la description
    op.drop_column('parcours_historique', 'Parcours_description_historique')
    
    # 🗑️ Suppression de la colonne pour l'abréviation
    op.drop_column('parcours_historique', 'Parcours_abbreviation_historique')
    
    # ### end Alembic commands ###